linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aquasecurity/)
      - blank
      - dot
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    disabled-checks:
      - appendAssign
      - unnamedResult
      - whyNoLint
      - indexAlloc
      - octalLiteral
      - hugeParam
      - rangeValCopy
      - regexpSimplify
      - sloppyReassign
      - commentedOutCode
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    settings:
      ruleguard:
        failOn: all
        rules: '${configDir}/misc/lint/rules.go'
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  gomodguard:
    blocked:
      modules:
        - github.com/hashicorp/go-version:
            recommendations:
              - github.com/aquasecurity/go-version
            reason: "`aquasecurity/go-version` is designed for our use-cases"
        - github.com/Masterminds/semver:
            recommendations:
              - github.com/aquasecurity/go-version
            reason: "`aquasecurity/go-version` is designed for our use-cases"
  gosec:
    excludes:
      - G101
      - G114
      - G204
      - G304
      - G402
  govet:
    check-shadowing: false
  misspell:
    locale: US
    ignore-words:
      - behaviour
      - licence
      - optimise
      - simmilar
  revive:
    ignore-generated-header: true
  testifylint:
    enable-all: true
    disable:
      - float-compare

linters:
  disable-all: true
  enable:
    - bodyclose
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unused

run:
  go: '1.22'
  timeout: 30m

issues:
  exclude-files:
    - "mock_*.go$"
    - "examples/*"
  exclude-dirs:
    - "pkg/iac/scanners/terraform/parser/funcs" # copies of Terraform functions
  exclude-rules:
    - path: ".*_test.go$"
      linters:
        - goconst
        - gosec
        - unused
    - path: ".*_test.go$"
      linters:
        - govet
      text: "copylocks:"
    - path: ".*_test.go$"
      linters:
        - gocritic
      text: "commentFormatting:"
    - path: ".*_test.go$"
      linters:
        - gocritic
      text: "exitAfterDefer:"
    - path: ".*_test.go$"
      linters:
        - gocritic
      text: "importShadow:"
  exclude-use-default: false
  max-same-issues: 0
